import type { Category, TimeEntry } from "./types"

export const mockCategories: Category[] = [
  {
    id: "1",
    name: "Work",
    weeklyBudget: 40,
    timeUsed: 22,
    color: "#2B93FA",
    subcategories: [
      {
        name: "Meetings",
        budget: 10,
        timeUsed: 5,
        goalDirection: "less_is_better",
        goalConfig: { threshold: 8 },
      },
      {
        name: "Deep Focus",
        budget: 15,
        timeUsed: 16,
        goalDirection: "more_is_better",
        goalConfig: { threshold: 18 },
      },
      {
        name: "Managing",
        budget: 5,
        timeUsed: 1,
        goalDirection: "target_range",
        goalConfig: { targetMin: 4, targetMax: 6 },
      },
      { name: "Other", budget: 10, timeUsed: 1, goalDirection: "target_range" },
    ],
  },
  {
    id: "2",
    name: "Personal",
    weeklyBudget: 7,
    timeUsed: 4,
    color: "#13B078",
    subcategories: [
      {
        name: "Domestic",
        budget: 3,
        timeUsed: 2,
        goalDirection: "target_range",
        goalConfig: { targetMin: 2.5, targetMax: 3.5 },
      },
      {
        name: "Family time",
        budget: 2,
        timeUsed: 1,
        goalDirection: "more_is_better",
        goalConfig: { threshold: 3 },
      },
      {
        name: "Hobbies",
        budget: 2,
        timeUsed: 1,
        goalDirection: "more_is_better",
        goalConfig: { threshold: 2.5 },
      },
    ],
  },
  {
    id: "3",
    name: "Exercise",
    weeklyBudget: 4,
    timeUsed: 2,
    color: "#EB8C5E",
    subcategories: [
      {
        name: "Cardio",
        budget: 2,
        timeUsed: 1,
        goalDirection: "more_is_better",
        goalConfig: { threshold: 2.5 },
      },
      {
        name: "Strength",
        budget: 2,
        timeUsed: 1,
        goalDirection: "more_is_better",
        goalConfig: { threshold: 2.5 },
      },
    ],
  },
  {
    id: "4",
    name: "Learning",
    weeklyBudget: 4,
    timeUsed: 1,
    color: "#6C63FF",
    subcategories: [
      {
        name: "Online courses",
        budget: 2,
        timeUsed: 1,
        goalDirection: "more_is_better",
        goalConfig: { threshold: 3 },
      },
      {
        name: "Reading",
        budget: 2,
        timeUsed: 0,
        goalDirection: "more_is_better",
        goalConfig: { threshold: 2.5 },
      },
    ],
  },
]

export const mockTimeEntries: TimeEntry[] = [
  {
    id: "1",
    categoryId: "1",
    categoryName: "Work",
    categoryColor: "#2B93FA",
    startTime: "09:00",
    endTime: "10:30",
    description: "Team standup and project planning",
    date: new Date().toISOString().split("T")[0],
    subcategory: "Meetings",
    notes: "Discussed Q2 roadmap and resource allocation",
    source: "slack",
    approved: false,
  },
  {
    id: "2",
    categoryId: "4",
    categoryName: "Learning",
    categoryColor: "#6C63FF",
    startTime: "14:00",
    endTime: "15:00",
    description: "React documentation review",
    date: new Date().toISOString().split("T")[0],
    subcategory: "Online courses",
    notes: "Focused on new hooks and performance optimization",
    source: "manual",
    approved: true,
  },
  {
    id: "3",
    categoryId: "3",
    categoryName: "Exercise",
    categoryColor: "#EB8C5E",
    startTime: "17:00",
    endTime: "18:00",
    description: "Gym workout",
    date: new Date().toISOString().split("T")[0],
    subcategory: "Strength",
    notes: "Upper body focus - chest and shoulders",
    source: "timer",
    approved: true,
  },
]
